import 'dart:io';
import 'dart:convert';

void main() {
  final defaultEnglish = {
    "appTitle": "Ringo Ringtones",
    "homeTab": "Home",
    "searchTab": "Search",
    "settingsTab": "Settings",
    "premiumTitle": "Ringo Premium",
    "premiumSubtitle": "Unlock all ringtones & features",
    "appearanceHeader": "Appearance",
    "darkMode": "Dark Mode",
    "dynamicColor": "Dynamic Color",
    "toolsHeader": "Tools",
    "ringtoneEditor": "Ringtone Editor",
    "generalHeader": "General",
    "language": "Language",
    "storage": "Storage",
    "legalHeader": "Legal & Support",
    "privacyPolicy": "Privacy Policy",
    "aboutUs": "About Us",
    "version": "Version",
    // UI Keys
    "searchHint": "Search ringtones...",
    "favoritesTitle": "Favorites",
    "noFavorites": "No favorites yet",
    "songsTitle": "Songs",
    "noSongs": "No songs found.",
    "latestTitle": "Latest",
    "seeMore": "See More",
    "noLatestRingtones": "No latest ringtones found.",
    "categoriesTitle": "Categories",
    "noCategories": "No categories found.",
    "typeToSearch": "Type to search",
    "noResults": "No results found",
    "roleDeveloper": "Developer",
    "roleAppOwner": "App Owner",
    "trendingTitle": "Trending Now",
    "noTrending": "No trending ringtones found.",
    
    // Detail Screen
    "detailSetRingtone": "Set Ringtone",
    "detailDownload": "Download",
    "detailEdit": "Edit",
    "detailSetAs": "Set as",
    "detailSetSuccess": "Successfully set as",
    "detailSetFailed": "Failed to set ringtone.",
    "dialogPremiumTitle": "Unlock Premium",
    "dialogPremiumContent": "Downloading is a Premium feature. Upgrade to unlock!",
    "dialogEditPremiumContent": "Editing is a Premium feature. Upgrade to unlock!",
    "btnCancel": "Cancel",
    "btnUpgrade": "Upgrade",
    "msgDownloading": "Downloading to Music...",
    "msgDownloadFailed": "Download failed",
    "msgSavedToMusic": "Saved to Music",
    "errorAudio": "Error loading audio",
    "permissionContact": "Permission denied to pick contact",
    "setAsRingtone": "Set as Ringtone",
    "setAsNotification": "Set as Notification",
    "setAsAlarm": "Set as Alarm",
    "setForContact": "Set for Contact",

    // Editor Screen
    "editorTitle": "Studio",
    "editorSet": "SET",
    "editorExport": "EXPORT",
    "editorImport": "IMPORT TRACK",
    "editorFadeIn": "Fade In",
    "editorFadeOut": "Fade Out",
    "editorSpeed": "Speed",
    "msgExportSuccess": "Exported successfully",
    "msgExportFailed": "Export failed",

    // Premium Screen
    "premiumUpgradeTitle": "Upgrade to Premium",
    "premiumUnlockDesc": "Unlock exclusive ringtones and features!",
    "planMonthly": "Monthly",
    "planYearly": "Yearly",
    "planLifetime": "Lifetime",
    "labelBestValue": "BEST VALUE",
    "linkRestorePurchase": "Restore Purchase",
    "btnSubscribe": "Subscribe",
    "msgPremiumWelcome": "Welcome to Ringo Premium!",
    "premiumAppBarTitle": "Ringo Premium",
    "periodMonth": "/ month",
    "periodYear": "/ year",
    "periodOneTime": "one-time",
    "requestRingtone": "Request Ringtone",
    "clearCache": "Clear Cache",
    "clearCacheSubtitle": "Free up space",
    "cacheCleared": "Cache cleared successfully",
    "showLess": "Show Less"
  };

  final Map<String, Map<String, String>> translations = {
    "en": {}, // Uses defaultEnglish
    "fr": {
      "appTitle": "Ringo Sonneries",
      "homeTab": "Accueil",
      "searchTab": "Recherche",
      "settingsTab": "Paramètres",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Débloquez tout",
      "appearanceHeader": "Apparence",
      "darkMode": "Mode sombre",
      "dynamicColor": "Couleur dynamique",
      "toolsHeader": "Outils",
      "ringtoneEditor": "Éditeur de sonnerie",
      "generalHeader": "Général",
      "language": "Langue",
      "storage": "Stockage",
      "legalHeader": "Mentions légales",
      "privacyPolicy": "Confidentialité",
      "aboutUs": "À propos",
      "version": "Version",
      "searchHint": "Rechercher des sonneries...",
      "favoritesTitle": "Favoris",
      "noFavorites": "Pas encore de favoris",
      "songsTitle": "Chansons",
      "noSongs": "Aucune chanson trouvée.",
      "latestTitle": "Derniers",
      "seeMore": "Voir plus",
      "noLatestRingtones": "Aucune sonnerie récente.",
      "categoriesTitle": "Catégories",
      "noCategories": "Aucune catégorie trouvée.",
      "typeToSearch": "Tapez pour rechercher",
      "noResults": "Aucun résultat",
      "roleDeveloper": "Développeur",
      "roleAppOwner": "Propriétaire",
      "trendingTitle": "Tendances",
      "noTrending": "Pas de sonneries tendance.",
      "detailSetRingtone": "Définir Sonnerie",
      "detailDownload": "Télécharger",
      "detailEdit": "Éditer",
      "detailSetAs": "Définir comme",
      "detailSetSuccess": "Défini avec succès comme",
      "detailSetFailed": "Échec de la définition.",
      "dialogPremiumTitle": "Débloquer Premium",
      "dialogPremiumContent": "Le téléchargement est une fonctionnalité Premium. Mettez à niveau !",
      "dialogEditPremiumContent": "L'édition est une fonctionnalité Premium. Mettez à niveau !",
      "btnCancel": "Annuler",
      "btnUpgrade": "Mettre à niveau",
      "btnSubscribe": "S'abonner",
      "msgDownloading": "Téléchargement...",
      "msgDownloadFailed": "Échec du téléchargement",
      "msgSavedToMusic": "Enregistré dans Musique",
      "errorAudio": "Erreur audio",
      "permissionContact": "Permission refusée",
      "setAsRingtone": "Définir comme Sonnerie",
      "setAsNotification": "Définir comme Notification",
      "setAsAlarm": "Définir comme Alarme",
      "setForContact": "Définir pour Contact",
      "editorTitle": "Studio",
      "editorSet": "DÉFINIR",
      "editorExport": "EXPORTER",
      "editorImport": "IMPORTER",
      "editorFadeIn": "Fondu Entrant",
      "editorFadeOut": "Fondu Sortant",
      "editorSpeed": "Vitesse",
      "msgExportSuccess": "Exporté avec succès",
      "msgExportFailed": "Échec de l'exportation",
      "premiumAppBarTitle": "Ringo Premium",
      "premiumUpgradeTitle": "Passer à Premium",
      "premiumUnlockDesc": "Débloquez tout !",
      "planMonthly": "Mensuel",
      "planYearly": "Annuel",
      "planLifetime": "À vie",
      "labelBestValue": "MEILLEUR",
      "linkRestorePurchase": "Restaurer",
      "msgPremiumWelcome": "Bienvenue !",
      "periodMonth": "/ mois",
      "periodYear": "/ an",
      "periodOneTime": "une fois",
      "requestRingtone": "Demander Sonnerie",
      "clearCache": "Vider Cache",
      "clearCacheSubtitle": "Libérer espace",
      "cacheCleared": "Cache vidé"
    },
    "de": {
      "appTitle": "Ringo Klingeltöne",
      "homeTab": "Startseite",
      "searchTab": "Suche",
      "settingsTab": "Einstellungen",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Alles freischalten",
      "appearanceHeader": "Aussehen",
      "darkMode": "Dunkelmodus",
      "dynamicColor": "Dynamische Farbe",
      "toolsHeader": "Werkzeuge",
      "ringtoneEditor": "Klingelton-Editor",
      "generalHeader": "Allgemein",
      "language": "Sprache",
      "storage": "Speicher",
      "legalHeader": "Rechtliches",
      "privacyPolicy": "Datenschutz",
      "aboutUs": "Über uns",
      "version": "Version",
      "searchHint": "Klingeltöne suchen...",
      "favoritesTitle": "Favoriten",
      "noFavorites": "Noch keine Favoriten",
      "songsTitle": "Lieder",
      "noSongs": "Keine Lieder gefunden.",
      "latestTitle": "Neueste",
      "seeMore": "Mehr sehen",
      "noLatestRingtones": "Keine neuesten Klingeltöne.",
      "categoriesTitle": "Kategorien",
      "noCategories": "Keine Kategorien gefunden.",
      "typeToSearch": "Tippen zum Suchen",
      "noResults": "Keine Ergebnisse",
      "roleDeveloper": "Entwickler",
      "roleAppOwner": "App-Inhaber",
      "trendingTitle": "Im Trend",
      "noTrending": "Keine Trend-Klingeltöne.",
      "detailSetRingtone": "Klingelton setzen",
      "detailDownload": "Laden",
      "detailEdit": "Bearbeiten",
      "detailSetAs": "Setzen als",
      "detailSetSuccess": "Erfolgreich gesetzt",
      "detailSetFailed": "Fehler beim Setzen",
      "dialogPremiumTitle": "Premium",
      "dialogPremiumContent": "Nur für Premium-Nutzer.",
      "dialogEditPremiumContent": "Nur für Premium-Nutzer.",
      "btnCancel": "Abbrechen",
      "btnUpgrade": "Upgrade",
      "btnSubscribe": "Abo",
      "msgDownloading": "Laden...",
      "msgDownloadFailed": "Fehler",
      "msgSavedToMusic": "Gespeichert",
      "errorAudio": "Audio-Fehler",
      "permissionContact": "Keine Berechtigung",
      "setAsRingtone": "Als Klingelton",
      "setAsNotification": "Als Benachrichtigung",
      "setAsAlarm": "Als Alarm",
      "setForContact": "Für Kontakt",
      "editorTitle": "Studio",
      "editorSet": "SETZEN",
      "editorExport": "EXPORT",
      "editorImport": "IMPORT",
      "editorFadeIn": "Fade In",
      "editorFadeOut": "Fade Out",
      "editorSpeed": "Tempo",
      "msgExportSuccess": "Exportiert",
      "msgExportFailed": "Export-Fehler",
      "premiumAppBarTitle": "Ringo Premium",
      "premiumUpgradeTitle": "Premium Upgrade",
      "premiumUnlockDesc": "Alles freischalten!",
      "planMonthly": "Monatlich",
      "planYearly": "Jährlich",
      "planLifetime": "Lebenslang",
      "labelBestValue": "BESTER WERT",
      "linkRestorePurchase": "Wiederherstellen",
      "msgPremiumWelcome": "Willkommen!",
      "periodMonth": "/ Monat",
      "periodYear": "/ Jahr",
      "periodOneTime": "einmalig",
      "requestRingtone": "Klingelton anfragen",
      "clearCache": "Cache leeren",
      "clearCacheSubtitle": "Speicher freigeben",
      "cacheCleared": "Cache geleert"
    },
    "it": {
      "appTitle": "Suonerie Ringo",
      "homeTab": "Home",
      "searchTab": "Cerca",
      "settingsTab": "Impostazioni",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Sblocca tutto",
      "appearanceHeader": "Aspetto",
      "darkMode": "Modalità scura",
      "dynamicColor": "Colore dinamico",
      "toolsHeader": "Strumenti",
      "ringtoneEditor": "Editor Suonerie",
      "generalHeader": "Generale",
      "language": "Lingua",
      "storage": "Archiviazione",
      "legalHeader": "Legale",
      "privacyPolicy": "Privacy",
      "aboutUs": "Chi siamo",
      "version": "Versione",
      "searchHint": "Cerca suonerie...",
      "favoritesTitle": "Preferiti",
      "noFavorites": "Nessun preferito",
      "songsTitle": "Canzoni",
      "noSongs": "Nessuna canzone trovata.",
      "latestTitle": "Ultimi",
      "seeMore": "Vedi altro",
      "noLatestRingtones": "Nessuna suoneria recente.",
      "categoriesTitle": "Categorie",
      "noCategories": "Nessuna categoria trovata.",
      "typeToSearch": "Digita per cercare",
      "noResults": "Nessun risultato",
      "roleDeveloper": "Sviluppatore",
      "roleAppOwner": "Proprietario",
      "trendingTitle": "Di Tendenza",
      "noTrending": "Nessuna suoneria di tendenza.",
      "detailSetRingtone": "Imposta Suoneria",
      "detailDownload": "Scarica",
      "detailEdit": "Modifica",
      "detailSetAs": "Imposta come",
      "detailSetSuccess": "Impostato con successo",
      "detailSetFailed": "Fallito",
      "dialogPremiumTitle": "Premium",
      "dialogPremiumContent": "Funzione Premium.",
      "dialogEditPremiumContent": "Funzione Premium.",
      "btnCancel": "Annulla",
      "btnUpgrade": "Upgrade",
      "btnSubscribe": "Abbonati",
      "msgDownloading": "Scaricando...",
      "msgDownloadFailed": "Fallito",
      "msgSavedToMusic": "Salvato",
      "errorAudio": "Errore Audio",
      "permissionContact": "Negato",
      "setAsRingtone": "Come Suoneria",
      "setAsNotification": "Come Notifica",
      "setAsAlarm": "Come Sveglia",
      "setForContact": "Per Contatto",
      "editorTitle": "Studio",
      "editorSet": "IMPOSTA",
      "editorExport": "EXPORT",
      "editorImport": "IMPORTA",
      "editorFadeIn": "Fade In",
      "editorFadeOut": "Fade Out",
      "editorSpeed": "Velocità",
      "msgExportSuccess": "Esportato",
      "msgExportFailed": "Errore Export",
      "premiumAppBarTitle": "Ringo Premium",
      "premiumUpgradeTitle": "Passa a Premium",
      "premiumUnlockDesc": "Sblocca tutto!",
      "planMonthly": "Mensile",
      "planYearly": "Annuale",
      "planLifetime": "A vita",
      "labelBestValue": "MIGLIORE",
      "linkRestorePurchase": "Ripristina",
      "msgPremiumWelcome": "Benvenuto!",
      "periodMonth": "/ mese",
      "periodYear": "/ anno",
      "periodOneTime": "una volta",
      "requestRingtone": "Richiedi Suoneria",
      "clearCache": "Svuota Cache",
      "clearCacheSubtitle": "Libera spazio",
      "cacheCleared": "Cache svuotata"
    },
    "es": {
      "appTitle": "Ringo Tonos",
      "homeTab": "Inicio",
      "searchTab": "Buscar",
      "settingsTab": "Ajustes",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Desbloquear todo",
      "appearanceHeader": "Apariencia",
      "darkMode": "Modo Oscuro",
      "dynamicColor": "Color Dinámico",
      "toolsHeader": "Herramientas",
      "ringtoneEditor": "Editor de Tonos",
      "generalHeader": "General",
      "language": "Idioma",
      "storage": "Almacenamiento",
      "legalHeader": "Legal",
      "privacyPolicy": "Política de Privacidad",
      "aboutUs": "Sobre Nosotros",
      "version": "Versión",
      "searchHint": "Buscar tonos...",
      "favoritesTitle": "Favoritos",
      "noFavorites": "Aún no hay favoritos",
      "songsTitle": "Canciones",
      "noSongs": "No se encontraron canciones.",
      "latestTitle": "Lo Último",
      "seeMore": "Ver más",
      "noLatestRingtones": "No se encontraron tonos recientes.",
      "categoriesTitle": "Categorías",
      "noCategories": "No se encontraron categorías.",
      "typeToSearch": "Escribe para buscar",
      "noResults": "Sin resultados",
      "roleDeveloper": "Desarrollador",
      "roleAppOwner": "Propietario",
      "trendingTitle": "Tendencias",
      "noTrending": "No hay tonos en tendencia.",
      "detailSetRingtone": "Establecer Tono",
      "detailDownload": "Descargar",
      "detailEdit": "Editar",
      "detailSetAs": "Establecer como",
      "detailSetSuccess": "Establecido como",
      "detailSetFailed": "Error al establecer tono.",
      "dialogPremiumTitle": "Desbloquear Premium",
      "dialogPremiumContent": "Descargar es función Premium. ¡Mejora para desbloquear!",
      "dialogEditPremiumContent": "Editar es función Premium. ¡Mejora para desbloquear!",
      "btnCancel": "Cancelar",
      "btnUpgrade": "Mejorar",
      "msgDownloading": "Descargando a Música...",
      "msgDownloadFailed": "Descarga fallida",
      "msgSavedToMusic": "Guardado en Música",
      "errorAudio": "Error al cargar audio",
      "permissionContact": "Permiso denegado para contactos",
      "setAsRingtone": "Establecer como Tono",
      "setAsNotification": "Establecer como Notificación",
      "setAsAlarm": "Establecer como Alarma",
      "setForContact": "Establecer para Contacto",
      "editorTitle": "Estudio",
      "editorSet": "SET",
      "editorExport": "EXPORTAR",
      "editorImport": "IMPORTAR",
      "editorFadeIn": "Fade In",
      "editorFadeOut": "Fade Out",
      "editorSpeed": "Velocidad",
      "msgExportSuccess": "Exportado con éxito",
      "msgExportFailed": "Error al exportar",
      "premiumUpgradeTitle": "Mejorar a Premium",
      "premiumUnlockDesc": "¡Desbloquea tonos y funciones exclusivas!",
      "planMonthly": "Mensual",
      "planYearly": "Anual",
      "planLifetime": "De por vida",
      "labelBestValue": "MEJOR VALOR",
      "linkRestorePurchase": "Restaurar Compra",
      "btnSubscribe": "Suscribirse",
      "msgPremiumWelcome": "¡Bienvenido a Ringo Premium!",
      "premiumAppBarTitle": "Ringo Premium",
      "periodMonth": "/ mes",
      "periodYear": "/ año",
      "periodOneTime": "pago único",
      "requestRingtone": "Solicitar Tono",
      "clearCache": "Borrar Caché",
      "clearCacheSubtitle": "Liberar espacio",
      "cacheCleared": "Caché borrada"
    },
    "hi": {
      "appTitle": "रिंगो रिंगटोन",
      "homeTab": "होम",
      "searchTab": "खोजें",
      "settingsTab": "सेटिंग्स",
      "premiumTitle": "रिंगो प्रीमियम",
      "premiumSubtitle": "सब कुछ अनलॉक करें",
      "appearanceHeader": "दिखावट",
      "darkMode": "डार्क मोड",
      "dynamicColor": "डायनामिक रंग",
      "toolsHeader": "टूल्स",
      "ringtoneEditor": "रिंगटोन एडिटर",
      "generalHeader": "सामान्य",
      "language": "भाषा",
      "storage": "स्टोरेज",
      "legalHeader": "कानूनी",
      "privacyPolicy": "गोपनीयता नीति",
      "aboutUs": "हमारे बारे में",
      "version": "वर्ज़न",
      "searchHint": "रिंगटोन खोजें...",
      "favoritesTitle": "पसंदीदा",
      "noFavorites": "अभी तक कोई पसंदीदा नहीं",
      "songsTitle": "गाने",
      "noSongs": "कोई गाना नहीं मिला",
      "latestTitle": "नवीनतम",
      "seeMore": "और देखें",
      "noLatestRingtones": "कोई नवीनतम रिंगटोन नहीं मिली",
      "categoriesTitle": "श्रेणियाँ",
      "noCategories": "कोई श्रेणी नहीं मिली",
      "typeToSearch": "खोजने के लिए टाइप करें",
      "noResults": "कोई परिणाम नहीं",
      "roleDeveloper": "डेवलपर",
      "roleAppOwner": "ऐप ओनर",
      "trendingTitle": "ट्रेंडिंग",
      "noTrending": "कोई ट्रेंडिंग रिंगटोन नहीं।",
      "detailSetRingtone": "रिंगटोन सेट करें",
      "detailDownload": "डाउनलोड",
      "detailEdit": "संपादित करें",
      "detailSetAs": "के रूप में सेट करें",
      "detailSetSuccess": "सफलतापूर्वक सेट किया गया",
      "detailSetFailed": "रिंगटोन सेट करने में विफल।",
      "dialogPremiumTitle": "प्रीमियम अनलॉक करें",
      "dialogPremiumContent": "डाउनलोड करना प्रीमियम फीचर है। अनलॉक करने के लिए अपग्रेड करें!",
      "dialogEditPremiumContent": "संपादन प्रीमियम फीचर है। अनलॉक करने के लिए अपग्रेड करें!",
      "btnCancel": "रद्द करें",
      "btnUpgrade": "अपग्रेड",
      "msgDownloading": "संगीत में डाउनलोड हो रहा है...",
      "msgDownloadFailed": "डाउनलोड विफल",
      "msgSavedToMusic": "संगीत में सहेजा गया",
      "errorAudio": "ऑडियो लोड करने में त्रुटि",
      "permissionContact": "संपर्क चुनने की अनुमति अस्वीकृत",
      "setAsRingtone": "रिंगटोन के रूप में सेट करें",
      "setAsNotification": "अधिसूचना के रूप में सेट करें",
      "setAsAlarm": "अलार्म के रूप में सेट करें",
      "setForContact": "संपर्क के लिए सेट करें",
      "editorTitle": "स्टूडियो",
      "editorSet": "सेट",
      "editorExport": "एक्सपोर्ट",
      "editorImport": "इम्पोर्ट ट्रैक",
      "editorFadeIn": "फेड इन",
      "editorFadeOut": "फेड आउट",
      "editorSpeed": "गति",
      "msgExportSuccess": "सफलतापूर्वक एक्सपोर्ट किया गया",
      "msgExportFailed": "एक्सपोर्ट विफल",
      "premiumUpgradeTitle": "प्रीमियम में अपग्रेड करें",
      "premiumUnlockDesc": "विशेष रिंगटोन और सुविधाएँ अनलॉक करें!",
      "planMonthly": "मासिक",
      "planYearly": "वार्षिक",
      "planLifetime": "आजीवन",
      "labelBestValue": "सर्वोत्तम मूल्य",
      "linkRestorePurchase": "खरीद बहाल करें",
      "btnSubscribe": "सदस्यता लें",
      "msgPremiumWelcome": "रिंगो प्रीमियम में आपका स्वागत है!",
      "premiumAppBarTitle": "रिंगो प्रीमियम",
      "periodMonth": "/ महीना",
      "periodYear": "/ साल",
      "periodOneTime": "एक बार",
      "requestRingtone": "रिंगटोन का अनुरोध करें",
      "clearCache": "कैश साफ़ करें",
      "clearCacheSubtitle": "स्थान खाली करें",
      "cacheCleared": "कैश साफ़ किया गया"
    },
    "pt": {
      "appTitle": "Toques Ringo",
      "homeTab": "Início",
      "searchTab": "Pesquisar",
      "settingsTab": "Configurações",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Desbloquear tudo",
      "appearanceHeader": "Aparência",
      "darkMode": "Modo Escuro",
      "dynamicColor": "Cor Dinâmica",
      "toolsHeader": "Ferramentas",
      "ringtoneEditor": "Editor de Toques",
      "generalHeader": "Geral",
      "language": "Idioma",
      "storage": "Armazenamento",
      "legalHeader": "Legal",
      "privacyPolicy": "Política de Privacidade",
      "aboutUs": "Sobre nós",
      "version": "Versão",
      "searchHint": "Pesquisar toques...",
      "favoritesTitle": "Favoritos",
      "noFavorites": "Ainda sem favoritos",
      "songsTitle": "Músicas",
      "noSongs": "Nenhuma música encontrada.",
      "latestTitle": "Mais recentes",
      "seeMore": "Ver mais",
      "noLatestRingtones": "Nenhum toque recente.",
      "categoriesTitle": "Categorias",
      "noCategories": "Nenhuma categoria encontrada.",
      "typeToSearch": "Digite para pesquisar",
      "noResults": "Nenhum resultado",
      "roleDeveloper": "Desenvolvedor",
      "roleAppOwner": "Proprietário",
      "trendingTitle": "Em Alta",
      "noTrending": "Nenhum toque em alta.",
      "requestRingtone": "Pedir Toque",
      "clearCache": "Limpar Cache",
      "clearCacheSubtitle": "Liberar espaço",
      "cacheCleared": "Cache limpo",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Assinar"
    },
    "ru": {
      "appTitle": "Рингтоны Ringo",
      "homeTab": "Главная",
      "searchTab": "Поиск",
      "settingsTab": "Настройки",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Разблокировать всё",
      "appearanceHeader": "Внешний вид",
      "darkMode": "Тёмная тема",
      "dynamicColor": "Динамический цвет",
      "toolsHeader": "Инструменты",
      "ringtoneEditor": "Редактор рингтонов",
      "generalHeader": "Общее",
      "language": "Язык",
      "storage": "Хранилище",
      "legalHeader": "Инфо",
      "privacyPolicy": "Политика конфиденциальности",
      "aboutUs": "О нас",
      "version": "Версия",
      "searchHint": "Поиск рингтонов...",
      "favoritesTitle": "Избранное",
      "noFavorites": "Нет избранных",
      "songsTitle": "Песни",
      "noSongs": "Песни не найдены.",
      "latestTitle": "Новые",
      "seeMore": "Показать еще",
      "noLatestRingtones": "Нет новых рингтонов.",
      "categoriesTitle": "Категории",
      "noCategories": "Категории не найдены.",
      "typeToSearch": "Введите для поиска",
      "noResults": "Нет результатов",
      "roleDeveloper": "Разработчик",
      "roleAppOwner": "Владелец",
      "trendingTitle": "В тренде",
      "noTrending": "Нет популярных рингтонов.",
      "requestRingtone": "Запросить рингтон",
      "clearCache": "Очистить кэш",
      "clearCacheSubtitle": "Освободить место",
      "cacheCleared": "Кэш очищен",
      "premiumAppBarTitle": "Ringo Премиум",
      "btnSubscribe": "Подписаться"
    },
    "ja": {
      "appTitle": "Ringo 着信音",
      "homeTab": "ホーム",
      "searchTab": "検索",
      "settingsTab": "設定",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "すべてをアンロック",
      "appearanceHeader": "外観",
      "darkMode": "ダークモード",
      "dynamicColor": "ダイナミックカラー",
      "toolsHeader": "ツール",
      "ringtoneEditor": "着信音エディタ",
      "generalHeader": "一般",
      "language": "言語",
      "storage": "ストレージ",
      "legalHeader": "法的事項",
      "privacyPolicy": "プライバシーポリシー",
      "aboutUs": "私たちについて",
      "version": "バージョン",
      "searchHint": "着信音を検索...",
      "favoritesTitle": "お気に入り",
      "noFavorites": "お気に入りはまだありません",
      "songsTitle": "曲",
      "noSongs": "曲が見つかりません。",
      "latestTitle": "最新",
      "seeMore": "もっと見る",
      "noLatestRingtones": "最新の着信音はありません。",
      "categoriesTitle": "カテゴリ",
      "noCategories": "カテゴリが見つかりません。",
      "typeToSearch": "検索キーワードを入力",
      "noResults": "結果なし",
      "roleDeveloper": "開発者",
      "roleAppOwner": "オーナー",
      "trendingTitle": "トレンド",
      "noTrending": "トレンドの着信音はありません。",
      "requestRingtone": "着信音をリクエスト",
      "clearCache": "キャッシュを消去",
      "clearCacheSubtitle": "空き容量を確保",
      "cacheCleared": "消去しました",
      "premiumAppBarTitle": "Ringoプレミアム",
      "btnSubscribe": "登録する"
    },
    "ko": {
      "appTitle": "Ringo 벨소리",
      "homeTab": "홈",
      "searchTab": "검색",
      "settingsTab": "설정",
      "premiumTitle": "Ringo 프리미엄",
      "premiumSubtitle": "모든 기능 잠금 해제",
      "appearanceHeader": "화면 스타일",
      "darkMode": "다크 모드",
      "dynamicColor": "다이내믹 컬러",
      "toolsHeader": "도구",
      "ringtoneEditor": "벨소리 편집기",
      "generalHeader": "일반",
      "language": "언어",
      "storage": "저장소",
      "legalHeader": "법적 고지",
      "privacyPolicy": "개인정보 처리방침",
      "aboutUs": "앱 정보",
      "version": "버전",
      "searchHint": "벨소리 검색...",
      "favoritesTitle": "즐겨찾기",
      "noFavorites": "즐겨찾기 없음",
      "songsTitle": "노래",
      "noSongs": "노래를 찾을 수 없음.",
      "latestTitle": "최신",
      "seeMore": "더 보기",
      "noLatestRingtones": "최신 벨소리 없음.",
      "categoriesTitle": "카테고리",
      "noCategories": "카테고리를 찾을 수 없음.",
      "typeToSearch": "검색어 입력",
      "noResults": "결과 없음",
      "roleDeveloper": "개발자",
      "roleAppOwner": "앱 소유자",
      "trendingTitle": "인기 급상승",
      "noTrending": "인기 벨소리 없음.",
      "requestRingtone": "벨소리 요청",
      "clearCache": "캐시 지우기",
      "clearCacheSubtitle": "공간 확보",
      "cacheCleared": "캐시가 삭제되었습니다",
      "premiumAppBarTitle": "Ringo 프리미엄",
      "btnSubscribe": "구독하다"
    },
    "zh": {
      "appTitle": "Ringo 铃声",
      "homeTab": "首页",
      "searchTab": "搜索",
      "settingsTab": "设置",
      "premiumTitle": "Ringo 高级版",
      "premiumSubtitle": "解锁所有功能",
      "appearanceHeader": "外观",
      "darkMode": "深色模式",
      "dynamicColor": "动态取色",
      "toolsHeader": "工具",
      "ringtoneEditor": "铃声编辑器",
      "generalHeader": "通用",
      "language": "语言",
      "storage": "存储",
      "legalHeader": "法律与支持",
      "privacyPolicy": "隐私政策",
      "aboutUs": "关于我们",
      "version": "版本",
      "searchHint": "搜索铃声...",
      "favoritesTitle": "收藏",
      "noFavorites": "暂无收藏",
      "songsTitle": "歌曲",
      "noSongs": "未找到歌曲。",
      "latestTitle": "最新",
      "seeMore": "查看更多",
      "noLatestRingtones": "暂无最新铃声。",
      "categoriesTitle": "分类",
      "noCategories": "未找到分类。",
      "typeToSearch": "输入以搜索",
      "noResults": "无结果",
      "roleDeveloper": "开发者",
      "roleAppOwner": "应用所有者",
      "trendingTitle": "热门趋势",
      "noTrending": "暂无热门铃声。",
      "requestRingtone": "请求铃声",
      "clearCache": "清除缓存",
      "clearCacheSubtitle": "释放空间",
      "cacheCleared": "缓存已清除",
      "premiumAppBarTitle": "Ringo 高级版",
      "btnSubscribe": "订阅"
    },
    "ar": {
      "appTitle": "نغمات Ringo",
      "homeTab": "الرئيسية",
      "searchTab": "بحث",
      "settingsTab": "الإعدادات",
      "premiumTitle": "Ringo بريميوم",
      "premiumSubtitle": "فتح كل الميزات",
      "appearanceHeader": "المظهر",
      "darkMode": "الوضع الداكن",
      "dynamicColor": "لون ديناميكي",
      "toolsHeader": "أدوات",
      "ringtoneEditor": "محرر النغمات",
      "generalHeader": "عام",
      "language": "اللغة",
      "storage": "التخزين",
      "legalHeader": "قانوني",
      "privacyPolicy": "سياسة الخصوصية",
      "aboutUs": "معلومات عنا",
      "version": "الإصدار",
      "searchHint": "بحث عن نغمات...",
      "favoritesTitle": "المفضلة",
      "noFavorites": "لا توجد مفضلة بعد",
      "songsTitle": "أغاني",
      "noSongs": "لم يتم العثور على أغاني.",
      "latestTitle": "أحدث",
      "seeMore": "شاهد المزيد",
      "noLatestRingtones": "لا توجد نغمات حديثة.",
      "categoriesTitle": "فئات",
      "noCategories": "لم يتم العثور على فئات.",
      "typeToSearch": "اكتب للبحث",
      "noResults": "لا توجد نتائج",
      "roleDeveloper": "مطور",
      "roleAppOwner": "مالك التطبيق",
      "trendingTitle": "شائع الآن",
      "noTrending": "لا توجد نغمات شائعة.",
      "requestRingtone": "طلب نغمة",
      "clearCache": "مسح ذاكرة التخزين المؤقت",
      "clearCacheSubtitle": "تحرير مساحة",
      "cacheCleared": "تم المسح",
      "premiumAppBarTitle": "رينغو بريميوم",
      "btnSubscribe": "اشتراك"
    },
    "tr": {
      "appTitle": "Ringo Zil Sesleri",
      "homeTab": "Ana Sayfa",
      "searchTab": "Ara",
      "settingsTab": "Ayarlar",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Tüm özelliklerin kilidini aç",
      "appearanceHeader": "Görünüm",
      "darkMode": "Karanlık Mod",
      "dynamicColor": "Dinamik Renk",
      "toolsHeader": "Araçlar",
      "ringtoneEditor": "Zil Sesi Düzenleyici",
      "generalHeader": "Genel",
      "language": "Dil",
      "storage": "Depolama",
      "legalHeader": "Yasal",
      "privacyPolicy": "Gizlilik Politikası",
      "aboutUs": "Hakkımızda",
      "version": "Sürüm",
      "searchHint": "Zil sesi ara...",
      "favoritesTitle": "Favoriler",
      "noFavorites": "Henüz favori yok",
      "songsTitle": "Şarkılar",
      "noSongs": "Şarkı bulunamadı.",
      "latestTitle": "En Yeni",
      "seeMore": "Daha Fazla",
      "noLatestRingtones": "Yeni zil sesi yok.",
      "categoriesTitle": "Kategoriler",
      "noCategories": "Kategori bulunamadı.",
      "typeToSearch": "Aramak için yazın",
      "noResults": "Sonuç yok",
      "roleDeveloper": "Geliştirici",
      "roleAppOwner": "Uygulama Sahibi",
      "trendingTitle": "Trendler",
      "noTrending": "Trend zil sesi yok.",
      "requestRingtone": "Zil Sesi İste",
      "clearCache": "Önbelleği Temizle",
      "clearCacheSubtitle": "Yer aç",
      "cacheCleared": "Temizlendi",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Abone Ol"
    },
    "id": {
      "appTitle": "Nada Dering Ringo",
      "homeTab": "Beranda",
      "searchTab": "Cari",
      "settingsTab": "Pengaturan",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Buka kunci semua fitur",
      "appearanceHeader": "Tampilan",
      "darkMode": "Mode Gelap",
      "dynamicColor": "Warna Dinamis",
      "toolsHeader": "Alat",
      "ringtoneEditor": "Editor Nada Dering",
      "generalHeader": "Umum",
      "language": "Bahasa",
      "storage": "Penyimpanan",
      "legalHeader": "Legal",
      "privacyPolicy": "Kebijakan Privasi",
      "aboutUs": "Tentang Kami",
      "version": "Versi",
      "searchHint": "Cari nada dering...",
      "favoritesTitle": "Favorit",
      "noFavorites": "Belum ada favorit",
      "songsTitle": "Lagu",
      "noSongs": "Lagu tidak ditemukan.",
      "latestTitle": "Terbaru",
      "seeMore": "Lihat Lebih",
      "noLatestRingtones": "Tidak ada nada dering terbaru.",
      "categoriesTitle": "Kategori",
      "noCategories": "Kategori tidak ditemukan.",
      "typeToSearch": "Ketik untuk mencari",
      "noResults": "Tidak ada hasil",
      "roleDeveloper": "Pengembang",
      "roleAppOwner": "Pemilik Aplikasi",
      "trendingTitle": "Sedang Tren",
      "noTrending": "Tidak ada nada dering tren.",
      "requestRingtone": "Minta Nada Dering",
      "clearCache": "Hapus Cache",
      "clearCacheSubtitle": "Kosongkan ruang",
      "cacheCleared": "Cache dihapus",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Langganan"
    },
    "vi": {
      "appTitle": "Nhạc chuông Ringo",
      "homeTab": "Trang chủ",
      "searchTab": "Tìm kiếm",
      "settingsTab": "Cài đặt",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Mở khóa tất cả tính năng",
      "appearanceHeader": "Giao diện",
      "darkMode": "Chế độ tối",
      "dynamicColor": "Màu động",
      "toolsHeader": "Công cụ",
      "ringtoneEditor": "Trình sửa nhạc chuông",
      "generalHeader": "Chung",
      "language": "Ngôn ngữ",
      "storage": "Lưu trữ",
      "legalHeader": "Pháp lý",
      "privacyPolicy": "Chính sách bảo mật",
      "aboutUs": "Về chúng tôi",
      "version": "Phiên bản",
      "searchHint": "Tìm nhạc chuông...",
      "favoritesTitle": "Yêu thích",
      "noFavorites": "Chưa có yêu thích",
      "songsTitle": "Bài hát",
      "noSongs": "Không tìm thấy bài hát.",
      "latestTitle": "Mới nhất",
      "seeMore": "Xem thêm",
      "noLatestRingtones": "Không có nhạc chuông mới.",
      "categoriesTitle": "Danh mục",
      "noCategories": "Không tìm thấy danh mục.",
      "typeToSearch": "Nhập để tìm",
      "noResults": "Không có kết quả",
      "roleDeveloper": "Nhà phát triển",
      "roleAppOwner": "Chủ sở hữu",
      "trendingTitle": "Xu hướng",
      "noTrending": "Không có nhạc chuông xu hướng.",
      "requestRingtone": "Yêu cầu Nhạc chuông",
      "clearCache": "Xóa bộ nhớ đệm",
      "clearCacheSubtitle": "Giải phóng dung lượng",
      "cacheCleared": "Đã xóa",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Đăng ký"
    },
    "nl": {
      "appTitle": "Ringo Ringtones",
      "homeTab": "Home",
      "searchTab": "Zoeken",
      "settingsTab": "Instellingen",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Alles ontgrendelen",
      "appearanceHeader": "Uiterlijk",
      "darkMode": "Donkere modus",
      "dynamicColor": "Dynamische kleur",
      "toolsHeader": "Hulpmiddelen",
      "ringtoneEditor": "Beltoon editor",
      "generalHeader": "Algemeen",
      "language": "Taal",
      "storage": "Opslag",
      "legalHeader": "Juridisch",
      "privacyPolicy": "Privacybeleid",
      "aboutUs": "Over ons",
      "version": "Versie",
      "searchHint": "Beltonen zoeken...",
      "favoritesTitle": "Favorieten",
      "noFavorites": "Nog geen favorieten",
      "songsTitle": "Liedjes",
      "noSongs": "Geen liedjes gevonden.",
      "latestTitle": "Nieuwste",
      "seeMore": "Bekijk meer",
      "noLatestRingtones": "Geen nieuwe beltonen.",
      "categoriesTitle": "Categorieën",
      "noCategories": "Geen categorieën gevonden.",
      "typeToSearch": "Typ om te zoeken",
      "noResults": "Geen resultaten",
      "roleDeveloper": "Ontwikkelaar",
      "roleAppOwner": "Eigenaar",
      "trendingTitle": "Nu viraal",
      "noTrending": "Geen virale ringtones.",
      "requestRingtone": "Ringtone Aanvragen",
      "clearCache": "Cache Wissen",
      "clearCacheSubtitle": "Maak ruimte vrij",
      "cacheCleared": "Cache gewist",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Abonneren"
    },
    "pl": {
      "appTitle": "Dzwonki Ringo",
      "homeTab": "Start",
      "searchTab": "Szukaj",
      "settingsTab": "Ustawienia",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Odblokuj wszystko",
      "appearanceHeader": "Wygląd",
      "darkMode": "Tryb ciemny",
      "dynamicColor": "Dynamiczny kolor",
      "toolsHeader": "Narzędzia",
      "ringtoneEditor": "Edytor dzwonków",
      "generalHeader": "Ogólne",
      "language": "Język",
      "storage": "Pamięć",
      "legalHeader": "Informacje prawne",
      "privacyPolicy": "Polityka prywatności",
      "aboutUs": "O nas",
      "version": "Wersja",
      "searchHint": "Szukaj dzwonków...",
      "favoritesTitle": "Ulubione",
      "noFavorites": "Brak ulubionych",
      "songsTitle": "Piosenki",
      "noSongs": "Nie znaleziono piosenek.",
      "latestTitle": "Najnowsze",
      "seeMore": "Zobacz więcej",
      "noLatestRingtones": "Brak nowych dzwonków.",
      "categoriesTitle": "Kategorie",
      "noCategories": "Nie znaleziono kategorii.",
      "typeToSearch": "Wpisz, aby wyszukać",
      "noResults": "Brak wyników",
      "roleDeveloper": "Programista",
      "roleAppOwner": "Właściciel",
      "trendingTitle": "Na czasie",
      "noTrending": "Brak dzwonków na czasie.",
      "requestRingtone": "Zaproponuj Dzwonek",
      "clearCache": "Wyczyść Pamięć",
      "clearCacheSubtitle": "Zwolnij miejsce",
      "cacheCleared": "Wyczyszczono",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Subskrybuj"
    },
    "uk": {
      "appTitle": "Рінгтони Ringo",
      "homeTab": "Головна",
      "searchTab": "Пошук",
      "settingsTab": "Налаштування",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Розблокувати все",
      "appearanceHeader": "Вигляд",
      "darkMode": "Темний режим",
      "dynamicColor": "Динамічний колір",
      "toolsHeader": "Інструменти",
      "ringtoneEditor": "Редактор рінгтонів",
      "generalHeader": "Загальні",
      "language": "Мова",
      "storage": "Сховище",
      "legalHeader": "Юридичні",
      "privacyPolicy": "Політика конфіденційності",
      "aboutUs": "Про нас",
      "version": "Версія",
      "searchHint": "Пошук рингтонів...",
      "favoritesTitle": "Вибране",
      "noFavorites": "Ще немає вибраного",
      "songsTitle": "Пісні",
      "noSongs": "Пісні не знайдено.",
      "latestTitle": "Нові",
      "seeMore": "Більше",
      "noLatestRingtones": "Немає нових рингтонів.",
      "categoriesTitle": "Категорії",
      "noCategories": "Категорії не знайдено.",
      "typeToSearch": "Введіть для пошуку",
      "noResults": "Нічого не знайдено",
      "roleDeveloper": "Розробник",
      "roleAppOwner": "Власник",
      "trendingTitle": "У тренді",
      "noTrending": "Немає трендів",
      "requestRingtone": "Запит на рингтон",
      "clearCache": "Очистити кеш",
      "clearCacheSubtitle": "Звільнити місце",
      "cacheCleared": "Кеш очищено",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Підписатися"
    },
    "sv": {
      "appTitle": "Ringo Ringsignaler",
      "homeTab": "Hem",
      "searchTab": "Sök",
      "settingsTab": "Inställningar",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Lås upp allt",
      "appearanceHeader": "Utseende",
      "darkMode": "Mörkt läge",
      "dynamicColor": "Dynamisk färg",
      "toolsHeader": "Verktyg",
      "ringtoneEditor": "Ringsignalredigerare",
      "generalHeader": "Allmänt",
      "language": "Språk",
      "storage": "Lagring",
      "legalHeader": "Juridisk",
      "privacyPolicy": "Integritetspolicy",
      "aboutUs": "Om oss",
      "version": "Version",
      "searchHint": "Sök ringsignaler...",
      "favoritesTitle": "Favoriter",
      "noFavorites": "Inga favoriter än",
      "songsTitle": "Låtar",
      "noSongs": "Inga låtar hittades.",
      "latestTitle": "Senaste",
      "seeMore": "Se mer",
      "noLatestRingtones": "Inga senaste ringsignaler.",
      "categoriesTitle": "Kategorier",
      "noCategories": "Inga kategorier hittades.",
      "typeToSearch": "Skriv för att söka",
      "noResults": "Inga resultat",
      "roleDeveloper": "Utvecklare",
      "roleAppOwner": "Ägare",
      "trendingTitle": "Trendar nu",
      "noTrending": "Inget trendar",
      "requestRingtone": "Begär ringsignal",
      "clearCache": "Rensa cache",
      "clearCacheSubtitle": "Frigör utrymme",
      "cacheCleared": "Cache rensad",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Prenumerera"
    },
    "cs": {
      "appTitle": "Ringo Vyzvánění",
      "homeTab": "Domů",
      "searchTab": "Hledat",
      "settingsTab": "Nastavení",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Odemknout vše",
      "appearanceHeader": "Vzhled",
      "darkMode": "Tmavý režim",
      "dynamicColor": "Dynamická barva",
      "toolsHeader": "Nástroje",
      "ringtoneEditor": "Editor vyzvánění",
      "generalHeader": "Obecné",
      "language": "Jazyk",
      "storage": "Plocha",
      "legalHeader": "Právní",
      "privacyPolicy": "Zásady ochrany osobních údajů",
      "aboutUs": "O nás",
      "version": "Verze",
      "searchHint": "Hledat vyzvánění...",
      "favoritesTitle": "Oblíbené",
      "noFavorites": "Zatím žádné oblíbené",
      "songsTitle": "Písně",
      "noSongs": "Nebyly nalezeny žádné písně.",
      "latestTitle": "Nejnovější",
      "seeMore": "Zobrazit více",
      "noLatestRingtones": "Žádné nejnovější vyzvánění.",
      "categoriesTitle": "Kategorie",
      "noCategories": "Nebyly nalezeny žádné kategorie.",
      "typeToSearch": "Pište pro hledání",
      "noResults": "Žádné výsledky",
      "roleDeveloper": "Vývojář",
      "roleAppOwner": "Vlastník",
      "trendingTitle": "Trendy",
      "noTrending": "Žádné trendy",
      "requestRingtone": "Žádost o vyzvánění",
      "clearCache": "Vymazat mezipaměť",
      "clearCacheSubtitle": "Uvolnit místo",
      "cacheCleared": "Mezipaměť vymazána",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Předplatit"
    },
    "el": {
      "appTitle": "Ringo Ringtones",
      "homeTab": "Αρχική",
      "searchTab": "Αναζήτηση",
      "settingsTab": "Ρυθμίσεις",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Ξεκλείδωμα όλων",
      "appearanceHeader": "Εμφάνιση",
      "darkMode": "Σκούρα λειτουργία",
      "dynamicColor": "Δυναμικό χρώμα",
      "toolsHeader": "Εργαλεία",
      "ringtoneEditor": "Επεξεργαστής ήχων",
      "generalHeader": "Γενικά",
      "language": "Γλώσσα",
      "storage": "Αποθήκευση",
      "legalHeader": "Νομικά",
      "privacyPolicy": "Πολιτική Απορρήτου",
      "aboutUs": "Σχετικά με εμάς",
      "version": "Έκδοση",
      "searchHint": "Αναζήτηση ήχων...",
      "favoritesTitle": "Αγαπημένα",
      "noFavorites": "Κανένα αγαπημένο ακόμα",
      "songsTitle": "Τραγούδια",
      "noSongs": "Δεν βρέθηκαν τραγούδια.",
      "latestTitle": "Τελευταία",
      "seeMore": "Δείτε περισσότερα",
      "noLatestRingtones": "Δεν βρέθηκαν πρόσφατοι ήχοι.",
      "categoriesTitle": "Κατηγορίες",
      "noCategories": "Δεν βρέθηκαν κατηγορίες.",
      "typeToSearch": "Πληκτρολογήστε για αναζήτηση",
      "noResults": "Κανένα αποτέλεσμα",
      "roleDeveloper": "Προγραμματιστής",
      "roleAppOwner": "Ιδιοκτήτης",
      "trendingTitle": "Δημοφιλή",
      "noTrending": "Κανένα δημοφιλές",
      "requestRingtone": "Αίτημα Ήχου",
      "clearCache": "Εκκαθάριση Cache",
      "clearCacheSubtitle": "Ελευθερώστε χώρο",
      "cacheCleared": "Εκκαθαρίστηκε",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Εγγραφή"
    },
    "ro": {
      "appTitle": "Tonuri Ringo",
      "homeTab": "Acasă",
      "searchTab": "Căutare",
      "settingsTab": "Setări",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Deblochează tot",
      "appearanceHeader": "Aspect",
      "darkMode": "Mod întunecat",
      "dynamicColor": "Culoare dinamică",
      "toolsHeader": "Instrumente",
      "ringtoneEditor": "Editor tonuri",
      "generalHeader": "General",
      "language": "Limbă",
      "storage": "Stocare",
      "legalHeader": "Legal",
      "privacyPolicy": "Politica de confidențialitate",
      "aboutUs": "Despre noi",
      "version": "Versiune",
      "searchHint": "Caută tonuri...",
      "favoritesTitle": "Favorite",
      "noFavorites": "Încă nu există favorite",
      "songsTitle": "Melodii",
      "noSongs": "Nu s-au găsit melodii.",
      "latestTitle": "Recente",
      "seeMore": "Vezi mai mult",
      "noLatestRingtones": "Nu există tonuri recente.",
      "categoriesTitle": "Categorii",
      "noCategories": "Nu s-au găsit categorii.",
      "typeToSearch": "Tastează pentru a căuta",
      "noResults": "Niciun rezultat",
      "roleDeveloper": "Dezvoltator",
      "roleAppOwner": "Proprietar",
      "trendingTitle": "În tendințe",
      "noTrending": "Nimic în tendințe",
      "requestRingtone": "Solicită Ton",
      "clearCache": "Șterge Cache",
      "clearCacheSubtitle": "Eliberează spațiu",
      "cacheCleared": "Cache șters",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Abonare"
    },
    "hu": {
      "appTitle": "Ringo Csengőhangok",
      "homeTab": "Kezdőlap",
      "searchTab": "Keresés",
      "settingsTab": "Beállítások",
      "premiumTitle": "Ringo Prémium",
      "premiumSubtitle": "Összes feloldása",
      "appearanceHeader": "Megjelenés",
      "darkMode": "Sötét mód",
      "dynamicColor": "Dinamikus szín",
      "toolsHeader": "Eszközök",
      "ringtoneEditor": "Csengőhang szerkesztő",
      "generalHeader": "Általános",
      "language": "Nyelv",
      "storage": "Tárhely",
      "legalHeader": "Jogi",
      "privacyPolicy": "Adatvédelmi irányelvek",
      "aboutUs": "Rólunk",
      "version": "Verzió",
      "searchHint": "Csengőhangok keresése...",
      "favoritesTitle": "Kedvencek",
      "noFavorites": "Még nincsenek kedvencek",
      "songsTitle": "Dalok",
      "noSongs": "Nem találhatók dalok.",
      "latestTitle": "Legújabb",
      "seeMore": "Többet mutat",
      "noLatestRingtones": "Nincsenek legújabb csengőhangok.",
      "categoriesTitle": "Kategóriák",
      "noCategories": "Nincsenek kategóriák.",
      "typeToSearch": "Írjon be a kereséshez",
      "noResults": "Nincs találat",
      "roleDeveloper": "Fejlesztő",
      "roleAppOwner": "Tulajdonos",
      "trendingTitle": "Felkapott",
      "noTrending": "Nincs felkapott",
      "requestRingtone": "Csengőhang kérése",
      "clearCache": "Gyorsítótár törlése",
      "clearCacheSubtitle": "Hely felszabadítása",
      "cacheCleared": "Törölve",
      "premiumAppBarTitle": "Ringo Prémium",
      "btnSubscribe": "Feliratkozás"
    },
    "da": {
      "appTitle": "Ringo Ringetoner",
      "homeTab": "Hjem",
      "searchTab": "Søg",
      "settingsTab": "Indstillinger",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Lås alt op",
      "appearanceHeader": "Udseende",
      "darkMode": "Mørk tilstand",
      "dynamicColor": "Dynamisk farve",
      "toolsHeader": "Værktøjer",
      "ringtoneEditor": "Ringetone editor",
      "generalHeader": "Generelt",
      "language": "Sprog",
      "storage": "Lager",
      "legalHeader": "Juridisk",
      "privacyPolicy": "Fortrolighedspolitik",
      "aboutUs": "Om os",
      "version": "Version",
      "searchHint": "Søg ringetoner...",
      "favoritesTitle": "Favoritter",
      "noFavorites": "Ingen favoritter endnu",
      "songsTitle": "Sange",
      "noSongs": "Ingen sange fundet.",
      "latestTitle": "Seneste",
      "seeMore": "Se mere",
      "noLatestRingtones": "Ingen seneste ringetoner.",
      "categoriesTitle": "Kategorier",
      "noCategories": "Ingen kategorier fundet.",
      "typeToSearch": "Skriv for at søge",
      "noResults": "Ingen resultater",
      "roleDeveloper": "Udvikler",
      "roleAppOwner": "Ejer",
      "trendingTitle": "Trender nu",
      "noTrending": "Ingen trends",
      "requestRingtone": "Anmod om ringetone",
      "clearCache": "Ryd cache",
      "clearCacheSubtitle": "Frigør plads",
      "cacheCleared": "Cache ryddet",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Abonner"
    },
    "fi": {
      "appTitle": "Ringo Soittoäänet",
      "homeTab": "Koti",
      "searchTab": "Haku",
      "settingsTab": "Asetukset",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Avaa kaikki",
      "appearanceHeader": "Ulkoasu",
      "darkMode": "Tumma tila",
      "dynamicColor": "Dynaaminen väri",
      "toolsHeader": "Työkalut",
      "ringtoneEditor": "Soittoäänen muokkain",
      "generalHeader": "Yleiset",
      "language": "Kieli",
      "storage": "Tallennustila",
      "legalHeader": "Lakitiedot",
      "privacyPolicy": "Tietosuojakäytäntö",
      "aboutUs": "Meistä",
      "version": "Versio",
      "searchHint": "Etsi soittoääniä...",
      "favoritesTitle": "Suosikit",
      "noFavorites": "Ei suosikkeja vielä",
      "songsTitle": "Kappaleet",
      "noSongs": "Kappaleita ei löytynyt.",
      "latestTitle": "Uusimmat",
      "seeMore": "Katso lisää",
      "noLatestRingtones": "Ei uusimpia soittoääniä.",
      "categoriesTitle": "Kategoriat",
      "noCategories": "Kategorioita ei löytynyt.",
      "typeToSearch": "Kirjoita etsiäksesi",
      "noResults": "Ei tuloksia",
      "roleDeveloper": "Kehittäjä",
      "roleAppOwner": "Omistaja",
      "trendingTitle": "Trendaavat",
      "noTrending": "Ei trendaavia",
      "requestRingtone": "Pyydä soittoääntä",
      "clearCache": "Tyhjennä välimuisti",
      "clearCacheSubtitle": "Vapauta tilaa",
      "cacheCleared": "Välimuisti tyhjennetty",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Tilaa"
    },
    "no": {
      "appTitle": "Ringo Ringetoner",
      "homeTab": "Hjem",
      "searchTab": "Søk",
      "settingsTab": "Innstillinger",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Lås opp alt",
      "appearanceHeader": "Utseende",
      "darkMode": "Mørk modus",
      "dynamicColor": "Dynamisk farge",
      "toolsHeader": "Verktøy",
      "ringtoneEditor": "Ringetoneredigerer",
      "generalHeader": "Generelt",
      "language": "Språk",
      "storage": "Lagring",
      "legalHeader": "Juridisk",
      "privacyPolicy": "Personvernerklæring",
      "aboutUs": "Om oss",
      "version": "Versjon",
      "searchHint": "Søk ringetoner...",
      "favoritesTitle": "Favoritter",
      "noFavorites": "Ingen favoritter ennå",
      "songsTitle": "Sanger",
      "noSongs": "Ingen sanger funnet.",
      "latestTitle": "Siste",
      "seeMore": "Se mer",
      "noLatestRingtones": "Ingen nye ringetoner.",
      "categoriesTitle": "Kategorier",
      "noCategories": "Ingen kategorier funnet.",
      "typeToSearch": "Skriv for å søke",
      "noResults": "Ingen resultater",
      "roleDeveloper": "Utvikler",
      "roleAppOwner": "Eier",
      "trendingTitle": "Trender nå",
      "noTrending": "Ingen trender",
      "requestRingtone": "Be om ringetone",
      "clearCache": "Tøm buffer",
      "clearCacheSubtitle": "Frigjør plass",
      "cacheCleared": "Buffer tømt",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Abonner"
    },
    "he": {
      "appTitle": "רינגו רינגטונים",
      "homeTab": "בית",
      "searchTab": "חיפוש",
      "settingsTab": "הגדרות",
      "premiumTitle": "Ringo פרימיום",
      "premiumSubtitle": "פתח הכל",
      "appearanceHeader": "מראה",
      "darkMode": "מצב כהה",
      "dynamicColor": "צבע דינמי",
      "toolsHeader": "כלים",
      "ringtoneEditor": "עורך רינגטונים",
      "generalHeader": "כללי",
      "language": "שפה",
      "storage": "אחסון",
      "legalHeader": "משפטי",
      "privacyPolicy": "מדיניות פרטיות",
      "aboutUs": "עלינו",
      "version": "גרסה",
      "searchHint": "חפש רינגטונים...",
      "favoritesTitle": "מועדפים",
      "noFavorites": "אין מועדפים עדיין",
      "songsTitle": "שירים",
      "noSongs": "לא נמצאו שירים.",
      "latestTitle": "חדש",
      "seeMore": "ראה עוד",
      "noLatestRingtones": "לא נמצאו רינגטונים חדשים.",
      "categoriesTitle": "קטגוריות",
      "noCategories": "לא נמצאו קטגוריות.",
      "typeToSearch": "הקלד לחיפוש",
      "noResults": "אין תוצאות",
      "roleDeveloper": "מפתח",
      "roleAppOwner": "בעלים",
      "trendingTitle": "פופולרי עכשיו",
      "noTrending": "אין פופולרי",
      "requestRingtone": "בקש רינגטון",
      "clearCache": "נקה מטמון",
      "clearCacheSubtitle": "פנה מקום",
      "cacheCleared": "המטמון נוקה",
      "premiumAppBarTitle": "Ringo פרימיום",
      "btnSubscribe": "הירשם"
    },
    "ms": {
      "appTitle": "Ringo Ringtones",
      "homeTab": "Utama",
      "searchTab": "Cari",
      "settingsTab": "Tetapan",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "Buka kunci semua",
      "appearanceHeader": "Penampilan",
      "darkMode": "Mod Gelap",
      "dynamicColor": "Warna Dinamik",
      "toolsHeader": "Alat",
      "ringtoneEditor": "Editor Nada Dering",
      "generalHeader": "Umum",
      "language": "Bahasa",
      "storage": "Penyimpanan",
      "legalHeader": "Undang-undang",
      "privacyPolicy": "Dasar Privasi",
      "aboutUs": "Tentang Kami",
      "version": "Versi",
      "searchHint": "Cari nada dering...",
      "favoritesTitle": "Kegemaran",
      "noFavorites": "Tiada kegemaran lagi",
      "songsTitle": "Lagu",
      "noSongs": "Tiada lagu ditemui.",
      "latestTitle": "Terkini",
      "seeMore": "Lihat Lagi",
      "noLatestRingtones": "Tiada nada dering terkini.",
      "categoriesTitle": "Kategori",
      "noCategories": "Tiada kategori ditemui.",
      "typeToSearch": "Taip untuk carian",
      "noResults": "Tiada hasil",
      "roleDeveloper": "Pembangun",
      "roleAppOwner": "Pemilik",
      "trendingTitle": "Sedang Arah",
      "noTrending": "Tiada trend",
      "requestRingtone": "Minta Nada Dering",
      "clearCache": "Kosongkan Cache",
      "clearCacheSubtitle": "Kosongkan ruang",
      "cacheCleared": "Cache dikosongkan",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "Langgan"
    },
    "bn": {
      "appTitle": "Ringo Ringtones",
      "homeTab": "হোম",
      "searchTab": "অনুসন্ধান",
      "settingsTab": "সেটিংস",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "সব আনলক করুন",
      "appearanceHeader": "চেহারা",
      "darkMode": "ডার্ক মোড",
      "dynamicColor": "ডাইনামিক কালার",
      "toolsHeader": "টুলস",
      "ringtoneEditor": "রিংটোন এডিটর",
      "generalHeader": "সাধারণ",
      "language": "ভাষা",
      "storage": "স্টোরেজ",
      "legalHeader": "আইনি",
      "privacyPolicy": "গোপনীয়তা নীতি",
      "aboutUs": "আমাদের সম্পর্কে",
      "version": "সংস্ক্ষণ",
      "searchHint": "রিংटोन অনুসন্ধান করুন...",
      "favoritesTitle": "প্রিয়",
      "noFavorites": "এখনও পছন্দের তালিকায় কিছু নেই",
      "songsTitle": "গান",
      "noSongs": "কোন গান পাওয়া যায়নি।",
      "latestTitle": "সর্বশেষ",
      "seeMore": "আরও দেখুন",
      "noLatestRingtones": "কোন নতুন রিংটোন পাওয়া যায়নি।",
      "categoriesTitle": "বিভাগ",
      "noCategories": "কোন বিভাগ পাওয়া যায়নি।",
      "typeToSearch": "অনুসন্ধান করতে লিখুন",
      "noResults": "কোন ফলাফল পাওয়া যায়নি",
      "roleDeveloper": "ডেভেলপার",
      "roleAppOwner": "মালিক",
      "trendingTitle": "এখন ট্রেন্ডিং",
      "noTrending": "কোন ট্রেন্ডিং নেই",
      "requestRingtone": "রিংটোন অনুরোধ করুন",
      "clearCache": "ক্যাশ মুছুন",
      "clearCacheSubtitle": "জায়গা খালি করুন",
      "cacheCleared": "ক্যাশ মুছে ফেলা হয়েছে",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "সাবস্ক্রাইব"
    },
    "ur": {
      "appTitle": "Ringo Ringtones",
      "homeTab": "ہوم",
      "searchTab": "تلاش",
      "settingsTab": "ترتیبات",
      "premiumTitle": "Ringo Premium",
      "premiumSubtitle": "سب ان لاک کریں",
      "appearanceHeader": "ظاہری شکل",
      "darkMode": "ڈارک موڈ",
      "dynamicColor": "متحرک رنگ",
      "toolsHeader": "اوزار",
      "ringtoneEditor": "رنگ ٹون ایڈیٹر",
      "generalHeader": "عام",
      "language": "زبان",
      "storage": "اسٹوریج",
      "legalHeader": "قانونی",
      "privacyPolicy": "رازداری کی پالیسی",
      "aboutUs": "ہمارے بارے میں",
      "version": "ورژن",
      "searchHint": "رنگ ٹونز تلاش کریں...",
      "favoritesTitle": "پسندیدہ",
      "noFavorites": "ابھی تک کوئی پسندیدہ نہیں",
      "songsTitle": "گانے",
      "noSongs": "کوئی گانا نہیں ملا۔",
      "latestTitle": "تازہ ترین",
      "seeMore": "مزید دیکھیں",
      "noLatestRingtones": "کوئی نئی رنگ ٹونز نہیں ملیں۔",
      "categoriesTitle": "زمرہ جات",
      "noCategories": "کوئی زمرہ نہیں ملا۔",
      "typeToSearch": "تلاش کرنے کے لیے ٹائپ کریں",
      "noResults": "کوئی نتیجہ نہیں",
      "roleDeveloper": "ڈویلپر",
      "roleAppOwner": "مالک",
      "trendingTitle": "ابھی مقبول",
      "noTrending": "کوئی مقبول نہیں",
      "requestRingtone": "رنگ ٹون کی درخواست کریں",
      "clearCache": "کیشے صاف کریں",
      "clearCacheSubtitle": "جگہ خالی کریں",
      "cacheCleared": "کیشے صاف ہو گیا",
      "premiumAppBarTitle": "Ringo Premium",
      "btnSubscribe": "سبסکرائب"
    },
    "th": {
      "appTitle": "เสียงเรียกเข้า Ringo",
      "homeTab": "หน้าแรก",
      "searchTab": "ค้นหา",
      "settingsTab": "การตั้งค่า",
      "premiumTitle": "Ringo พรีเมียม",
      "premiumSubtitle": "ปลดล็อกทั้งหมด",
      "appearanceHeader": "รูปร่างหน้าตา",
      "darkMode": "โหมดมืด",
      "dynamicColor": "สีไดนามิก",
      "toolsHeader": "เครื่องมือ",
      "ringtoneEditor": "ตัวแก้ไขเสียงเรียกเข้า",
      "generalHeader": "ทั่วไป",
      "language": "ภาษา",
      "storage": "พื้นที่จัดเก็บ",
      "legalHeader": "กฎหมาย",
      "privacyPolicy": "นโยบายความเป็นส่วนตัว",
      "aboutUs": "เกี่ยวกับเรา",
      "version": "เวอร์ชัน",
      "searchHint": "ค้นหาเสียงเรียกเข้า...",
      "favoritesTitle": "รายการโปรด",
      "noFavorites": "ยังไม่มีรายการโปรด",
      "songsTitle": "เพลง",
      "noSongs": "ไม่พบเพลง",
      "latestTitle": "ล่าสุด",
      "seeMore": "ดูเพิ่มเติม",
      "noLatestRingtones": "ไม่พบเสียงเรียกเข้าล่าสุด",
      "categoriesTitle": "หมวดหมู่",
      "noCategories": "ไม่พบหมวดหมู่",
      "typeToSearch": "พิมพ์เพื่อค้นหา",
      "noResults": "ไม่พบผลลัพธ์",
      "roleDeveloper": "นักพัฒนา",
      "roleAppOwner": "เจ้าของแอป",
      "trendingTitle": "กำลังมาแรง",
      "noTrending": "ไม่พบเสียงเรียกเข้า",
      "requestRingtone": "ขอเสียงเรียกเข้า",
      "clearCache": "ล้างแคช",
      "clearCacheSubtitle": "เพิ่มพื้นที่ว่าง",
      "cacheCleared": "ล้างแคชแล้ว",
      "premiumAppBarTitle": "Ringo พรีเมียม",
      "btnSubscribe": "สมัครสมาชิก"
    }
  };

  translations.forEach((lang, keys) {
    // Merge with default to ensure no missing keys
    final merged = Map<String, String>.from(defaultEnglish);
    merged.addAll(keys);
    merged["@@locale"] = lang;

    final file = File("lib/l10n/arb/app_$lang.arb");
    file.writeAsStringSync(const JsonEncoder.withIndent('    ').convert(merged));
    print("Updated app_$lang.arb");
  });
}
